repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0  # Use the latest stable version
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        entry: golangci-lint run --config .golangci-lint.yaml
        language: system
        types: [go]
        pass_filenames: false
