repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
        name: golangci-lint (gofmt only)
        entry: golangci-lint run --config .golangci-lint.yaml
        language: system
        types: [go]
        pass_filenames: false
